# Generated by Django 5.0.3 on 2024-03-14 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_followup_created_date_alter_job_applied_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 2, 20, 43, 563519), verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='job',
            name='applied_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 2, 20, 43, 557990), verbose_name='date applied'),
        ),
    ]
