# Generated by Django 5.0.3 on 2024-03-14 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_followup_created_date_alter_job_applied_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 3, 3, 26, 686000), verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='due_date',
            field=models.DateTimeField(null=True, verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='applied_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 3, 3, 26, 680434), verbose_name='date applied'),
        ),
    ]
