# Generated by Django 5.0.3 on 2024-06-16 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_alter_followup_created_date_alter_followup_due_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="multiple",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="multiple_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="followup",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 16, 14, 20, 36, 501616),
                verbose_name="date added",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="applied_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 16, 14, 20, 36, 492754),
                verbose_name="date applied",
            ),
        ),
    ]
